spring:
  datasource:
    platform: mariadb
    url: jdbc:mariadb://localhost:3306/study
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: "1111"
    hikari:      pool-name: ex1-hikari-pool
      maximum-pool-size: 10
      connection-init-sql: select 1
  jpa:
    database: mysql
    #InnoDB 설정
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    #기본설정, MyISAM
    #database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: false
    hibernate:
      ddl-auto: update
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        #physical-strategy: com.skcc.jpa.UpperSnakeCasePhysicalNamingStrategy
    show-sql: true